#!/bin/bash
set -euo pipefail

server_version() {
  docker version -f "{{.Server.Version}}"
}

supports_detach_option=false
if [[ "$(server_version)" > "17.05" ]]; then
  supports_detach_option=true
  echo "Enabling synchronous service updates"
fi

detach_option=""

[ $supports_detach_option = true ] && detach_option="--detach=false"

for service in $(IFS="\n" docker service ls --quiet); do
  name="$(docker service inspect "$service" -f '{{.Spec.Name}}')"
  image_with_digest="$(docker service inspect "$service" -f '{{.Spec.TaskTemplate.ContainerSpec.Image}}')"
  image=$(echo "$image_with_digest" | cut -d@ -f1)
  if [[ " $image " = " $1 " ]]; then
    echo "Updating service $name with image $image"
  fi
done