#!/bin/bash
set -euo pipefail

for service in $(IFS="\n" docker service ls --quiet); do
  name="$(docker service inspect "$service" -f '{{.Spec.Name}}')"
  image_with_digest="$(docker service inspect "$service" -f '{{.Spec.TaskTemplate.ContainerSpec.Image}}')"
  image=$(echo "$image_with_digest" | cut -d@ -f1)
  if [[ " $image " = " $1 " ]]; then
    echo "Updating service $name with image $image"
    docker service update "$service" --with-registry-auth --image="$image" > /dev/null
  fi
done